BEGIN;

-- Stage A+B identity and access-management foundation.
--
-- PostgreSQL TIMESTAMPTZ stores an absolute instant (UTC internally).  The
-- application must format it for the user's timezone; no local wall-clock
-- timestamps are stored in these tables.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS platform;
CREATE SCHEMA IF NOT EXISTS iam;

CREATE TABLE IF NOT EXISTS platform.schema_migration (
  migration_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migration_key text NOT NULL UNIQUE,
  version integer NOT NULL UNIQUE CHECK (version > 0),
  checksum char(64) NOT NULL CHECK (checksum ~ '^[0-9a-fA-F]{64}$'),
  applied_at timestamptz NOT NULL DEFAULT now(),
  applied_by text NOT NULL DEFAULT current_user,
  notes text
);

COMMENT ON TABLE platform.schema_migration IS
  'Applied database migrations. checksum is a stable migration-contract hash; rerunning a migration with a different checksum fails.';
COMMENT ON COLUMN platform.schema_migration.applied_at IS
  'Absolute UTC instant. PostgreSQL TIMESTAMPTZ is used intentionally.';

DO $$
BEGIN
  CREATE TYPE iam.user_status AS ENUM ('ACTIVE', 'SUSPENDED', 'DELETED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE iam.membership_status AS ENUM ('INVITED', 'ACTIVE', 'SUSPENDED', 'REMOVED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE iam.role_scope AS ENUM ('SYSTEM', 'ORGANIZATION');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE iam.invitation_status AS ENUM ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS iam.user_account (
  user_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  identity_provider text NOT NULL DEFAULT 'local',
  external_subject text,
  email text,
  display_name text,
  status iam.user_status NOT NULL DEFAULT 'ACTIVE',
  email_verified boolean NOT NULL DEFAULT false,
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (btrim(identity_provider) <> ''),
  CHECK (external_subject IS NULL OR btrim(external_subject) <> ''),
  CHECK (email IS NULL OR (btrim(email) = email AND position('@' IN email) > 1)),
  CHECK (display_name IS NULL OR btrim(display_name) <> '')
);

COMMENT ON TABLE iam.user_account IS
  'Application identity. OIDC/provider subject is the durable external identity key; no provider access token is stored here.';
COMMENT ON COLUMN iam.user_account.external_subject IS
  'Stable subject identifier from the configured identity provider, not an access token.';
COMMENT ON COLUMN iam.user_account.updated_at IS
  'Absolute UTC instant.';

CREATE TABLE IF NOT EXISTS iam.organization (
  organization_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_key text NOT NULL UNIQUE,
  organization_name text NOT NULL,
  legal_name text,
  status iam.user_status NOT NULL DEFAULT 'ACTIVE',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (organization_key ~ '^[a-zA-Z0-9][a-zA-Z0-9_-]{1,99}$'),
  CHECK (btrim(organization_name) <> ''),
  CHECK (legal_name IS NULL OR btrim(legal_name) <> '')
);

COMMENT ON TABLE iam.organization IS
  'Tenant boundary for enterprise projects, BOMs, calculations, conversations and uploads.';

CREATE TABLE IF NOT EXISTS iam.organization_membership (
  membership_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL
    REFERENCES iam.organization(organization_id) ON DELETE CASCADE,
  user_id uuid NOT NULL
    REFERENCES iam.user_account(user_id) ON DELETE CASCADE,
  membership_status iam.membership_status NOT NULL DEFAULT 'ACTIVE',
  joined_at timestamptz,
  invited_by uuid REFERENCES iam.user_account(user_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, user_id),
  CHECK (joined_at IS NULL OR joined_at >= created_at)
);

COMMENT ON TABLE iam.organization_membership IS
  'A user-to-organization membership. All tenant-scoped authorization resolves through this row.';

CREATE TABLE IF NOT EXISTS iam.role (
  role_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  role_key text NOT NULL UNIQUE,
  role_name_cn text NOT NULL,
  role_name_en text NOT NULL,
  role_scope iam.role_scope NOT NULL DEFAULT 'ORGANIZATION',
  description text,
  is_system_role boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (role_key ~ '^[a-z][a-z0-9_.-]{1,99}$'),
  CHECK (btrim(role_name_cn) <> ''),
  CHECK (btrim(role_name_en) <> '')
);

CREATE TABLE IF NOT EXISTS iam.permission (
  permission_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  permission_key text NOT NULL UNIQUE,
  resource_key text NOT NULL,
  action_key text NOT NULL,
  permission_name_cn text NOT NULL,
  permission_name_en text NOT NULL,
  description text,
  is_system_permission boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (permission_key ~ '^[a-z][a-z0-9_.-]{1,99}$'),
  CHECK (resource_key ~ '^[a-z][a-z0-9_.-]{0,49}$'),
  CHECK (action_key ~ '^[a-z][a-z0-9_.-]{0,49}$'),
  CHECK (btrim(permission_name_cn) <> ''),
  CHECK (btrim(permission_name_en) <> '')
);

CREATE TABLE IF NOT EXISTS iam.role_permission (
  role_id uuid NOT NULL
    REFERENCES iam.role(role_id) ON DELETE CASCADE,
  permission_id uuid NOT NULL
    REFERENCES iam.permission(permission_id) ON DELETE CASCADE,
  granted_at timestamptz NOT NULL DEFAULT now(),
  granted_by uuid REFERENCES iam.user_account(user_id) ON DELETE SET NULL,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS iam.membership_role (
  membership_id uuid NOT NULL
    REFERENCES iam.organization_membership(membership_id) ON DELETE CASCADE,
  role_id uuid NOT NULL
    REFERENCES iam.role(role_id) ON DELETE RESTRICT,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  assigned_by uuid REFERENCES iam.user_account(user_id) ON DELETE SET NULL,
  PRIMARY KEY (membership_id, role_id)
);

CREATE TABLE IF NOT EXISTS iam.session (
  session_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL
    REFERENCES iam.user_account(user_id) ON DELETE CASCADE,
  session_token_hash char(64) NOT NULL UNIQUE,
  auth_provider text NOT NULL DEFAULT 'local',
  created_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  ip_address inet,
  user_agent text,
  CHECK (session_token_hash ~ '^[0-9a-fA-F]{64}$'),
  CHECK (btrim(auth_provider) <> ''),
  CHECK (expires_at > created_at),
  CHECK (last_seen_at >= created_at),
  CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

-- A session has one explicit active organization context.  Membership is
-- checked by the application on every request; this nullable pointer allows
-- a user with memberships in multiple organizations to switch context while
-- keeping the session itself tenant-aware.
ALTER TABLE iam.session
  ADD COLUMN IF NOT EXISTS current_organization_id uuid
    REFERENCES iam.organization(organization_id) ON DELETE SET NULL;

COMMENT ON TABLE iam.session IS
  'Server-side session registry. Store only a SHA-256 token hash; the raw cookie token never enters PostgreSQL.';
COMMENT ON COLUMN iam.session.expires_at IS
  'Absolute UTC expiration instant.';
COMMENT ON COLUMN iam.session.current_organization_id IS
  'Current organization context selected for this session; application must verify an active membership before use.';

CREATE TABLE IF NOT EXISTS iam.invitation (
  invitation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL
    REFERENCES iam.organization(organization_id) ON DELETE CASCADE,
  email text NOT NULL,
  invitation_token_hash char(64) NOT NULL UNIQUE,
  invited_by uuid REFERENCES iam.user_account(user_id) ON DELETE SET NULL,
  role_id uuid REFERENCES iam.role(role_id) ON DELETE RESTRICT,
  invitation_status iam.invitation_status NOT NULL DEFAULT 'PENDING',
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  accepted_by uuid REFERENCES iam.user_account(user_id) ON DELETE SET NULL,
  revoked_at timestamptz,
  CHECK (btrim(email) = email AND position('@' IN email) > 1),
  CHECK (invitation_token_hash ~ '^[0-9a-fA-F]{64}$'),
  CHECK (expires_at > created_at),
  CHECK (accepted_at IS NULL OR accepted_at >= created_at),
  CHECK (revoked_at IS NULL OR revoked_at >= created_at),
  CHECK (NOT (accepted_at IS NOT NULL AND revoked_at IS NOT NULL))
);

COMMENT ON TABLE iam.invitation IS
  'One-time organization invitation. Only a token hash is stored; invitation acceptance is auditable through timestamps and user references.';

CREATE INDEX IF NOT EXISTS idx_user_account_status
  ON iam.user_account(status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_account_provider_subject
  ON iam.user_account(identity_provider, external_subject)
  WHERE external_subject IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_account_email_ci
  ON iam.user_account(lower(email))
  WHERE email IS NOT NULL AND status <> 'DELETED'::iam.user_status;

CREATE INDEX IF NOT EXISTS idx_membership_user_status
  ON iam.organization_membership(user_id, membership_status);
CREATE INDEX IF NOT EXISTS idx_membership_org_status
  ON iam.organization_membership(organization_id, membership_status);

CREATE INDEX IF NOT EXISTS idx_role_scope
  ON iam.role(role_scope, role_key);
CREATE INDEX IF NOT EXISTS idx_permission_resource
  ON iam.permission(resource_key, action_key);
CREATE INDEX IF NOT EXISTS idx_role_permission_permission
  ON iam.role_permission(permission_id, role_id);
CREATE INDEX IF NOT EXISTS idx_membership_role_role
  ON iam.membership_role(role_id, membership_id);

CREATE INDEX IF NOT EXISTS idx_session_user_active
  ON iam.session(user_id, expires_at)
  WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_session_current_organization
  ON iam.session(current_organization_id, user_id)
  WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_session_expiry
  ON iam.session(expires_at)
  WHERE revoked_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_invitation_org_email_pending
  ON iam.invitation(organization_id, lower(email))
  WHERE invitation_status = 'PENDING'::iam.invitation_status
    AND revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_invitation_expiry
  ON iam.invitation(expires_at, invitation_status);

CREATE OR REPLACE FUNCTION platform.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_touch_user_account_updated_at ON iam.user_account;
CREATE TRIGGER trg_touch_user_account_updated_at
BEFORE UPDATE ON iam.user_account
FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

DROP TRIGGER IF EXISTS trg_touch_organization_updated_at ON iam.organization;
CREATE TRIGGER trg_touch_organization_updated_at
BEFORE UPDATE ON iam.organization
FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

DROP TRIGGER IF EXISTS trg_touch_membership_updated_at ON iam.organization_membership;
CREATE TRIGGER trg_touch_membership_updated_at
BEFORE UPDATE ON iam.organization_membership
FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

DROP TRIGGER IF EXISTS trg_touch_role_updated_at ON iam.role;
CREATE TRIGGER trg_touch_role_updated_at
BEFORE UPDATE ON iam.role
FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

DROP TRIGGER IF EXISTS trg_touch_permission_updated_at ON iam.permission;
CREATE TRIGGER trg_touch_permission_updated_at
BEFORE UPDATE ON iam.permission
FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

-- Stage A+B system roles.  They are seed data, not a substitute for an
-- organization's membership assignment; every private API must resolve the
-- current user and organization before checking these permissions.
INSERT INTO iam.role (
  role_key, role_name_cn, role_name_en, role_scope, description, is_system_role
)
VALUES
  ('system_admin', '系统管理员', 'System administrator', 'SYSTEM',
   'Platform-wide administration and emergency recovery.', true),
  ('org_admin', '组织管理员', 'Organization administrator', 'ORGANIZATION',
   'Manage organization members, roles and organization data.', true),
  ('policy_editor', '政策编辑员', 'Policy editor', 'ORGANIZATION',
   'Create and update policy, tariff and evidence drafts.', true),
  ('policy_reviewer', '政策审核员', 'Policy reviewer', 'ORGANIZATION',
   'Review and publish policy and evidence changes.', true),
  ('analyst', '分析员', 'Analyst', 'ORGANIZATION',
   'Run calculations and use the decision assistant.', true),
  ('project_manager', '项目经理', 'Project manager', 'ORGANIZATION',
   'Manage enterprise projects, BOMs and calculation scenarios.', true),
  ('viewer', '只读用户', 'Viewer', 'ORGANIZATION',
   'Read approved policy and organization-scoped results.', true),
  ('audit_reader', '审计读取者', 'Audit reader', 'ORGANIZATION',
   'Read audit, evidence and calculation trace data.', true)
ON CONFLICT (role_key) DO UPDATE SET
  role_name_cn = EXCLUDED.role_name_cn,
  role_name_en = EXCLUDED.role_name_en,
  role_scope = EXCLUDED.role_scope,
  description = EXCLUDED.description,
  is_system_role = EXCLUDED.is_system_role,
  updated_at = now();

INSERT INTO iam.permission (
  permission_key, resource_key, action_key,
  permission_name_cn, permission_name_en, description, is_system_permission
)
VALUES
  ('policy.read', 'policy', 'read', '读取政策', 'Read policies', 'Read active and permitted policy records.', true),
  ('policy.create', 'policy', 'create', '创建政策', 'Create policies', 'Create policy drafts.', true),
  ('policy.update', 'policy', 'update', '更新政策', 'Update policies', 'Update policy drafts and metadata.', true),
  ('policy.publish', 'policy', 'publish', '发布政策', 'Publish policies', 'Approve and publish verified policy changes.', true),
  ('evidence.read', 'evidence', 'read', '读取证据', 'Read evidence', 'Read source documents and clauses.', true),
  ('evidence.manage', 'evidence', 'manage', '管理证据', 'Manage evidence', 'Ingest, verify and maintain evidence.', true),
  ('classification.read', 'classification', 'read', '读取归类', 'Read classification', 'Read classification and HS mappings.', true),
  ('calculation.run', 'calculation', 'run', '运行计算', 'Run calculations', 'Run CBU/CKD calculations.', true),
  ('calculation.read', 'calculation', 'read', '读取计算', 'Read calculations', 'Read calculation results and traces.', true),
  ('project.read', 'project', 'read', '读取项目', 'Read projects', 'Read organization projects.', true),
  ('project.create', 'project', 'create', '创建项目', 'Create projects', 'Create decision projects.', true),
  ('project.update', 'project', 'update', '更新项目', 'Update projects', 'Update project inputs and approvals.', true),
  ('project.delete', 'project', 'delete', '删除项目', 'Delete projects', 'Archive or delete permitted projects.', true),
  ('bom.read', 'bom', 'read', '读取BOM', 'Read BOMs', 'Read BOM structures and tariff selections.', true),
  ('bom.update', 'bom', 'update', '更新BOM', 'Update BOMs', 'Maintain BOM inputs and allocations.', true),
  ('assistant.chat', 'assistant', 'chat', '使用AI助手', 'Use assistant', 'Create and continue assistant conversations.', true),
  ('assistant.upload', 'assistant', 'upload', '上传助手附件', 'Upload assistant files', 'Upload files/images for an assistant run.', true),
  ('assistant.web_search', 'assistant', 'web_search', '使用联网搜索', 'Use web search', 'Run approved external web-search tools.', true),
  ('conversation.read_own', 'conversation', 'read_own', '读取个人对话', 'Read own conversations', 'Read conversations owned by the current user.', true),
  ('conversation.read_org', 'conversation', 'read_org', '读取组织对话', 'Read organization conversations', 'Read organization conversations subject to policy.', true),
  ('conversation.archive', 'conversation', 'archive', '归档对话', 'Archive conversations', 'Archive permitted conversations.', true),
  ('member.read', 'member', 'read', '读取成员', 'Read members', 'Read organization membership records.', true),
  ('member.manage', 'member', 'manage', '管理成员', 'Manage members', 'Invite, suspend and remove members.', true),
  ('role.manage', 'role', 'manage', '管理角色', 'Manage roles', 'Assign permitted roles to memberships.', true),
  ('audit.read', 'audit', 'read', '读取审计', 'Read audit', 'Read security and decision audit trails.', true),
  ('system.manage', 'system', 'manage', '管理系统', 'Manage system', 'Manage platform-level settings and recovery.', true)
ON CONFLICT (permission_key) DO UPDATE SET
  resource_key = EXCLUDED.resource_key,
  action_key = EXCLUDED.action_key,
  permission_name_cn = EXCLUDED.permission_name_cn,
  permission_name_en = EXCLUDED.permission_name_en,
  description = EXCLUDED.description,
  is_system_permission = EXCLUDED.is_system_permission,
  updated_at = now();

WITH role_permissions(role_key, permission_key) AS (
  VALUES
    ('system_admin', 'system.manage'),
    ('system_admin', 'policy.read'), ('system_admin', 'policy.create'),
    ('system_admin', 'policy.update'), ('system_admin', 'policy.publish'),
    ('system_admin', 'evidence.read'), ('system_admin', 'evidence.manage'),
    ('system_admin', 'classification.read'), ('system_admin', 'calculation.run'),
    ('system_admin', 'calculation.read'), ('system_admin', 'project.read'),
    ('system_admin', 'project.create'), ('system_admin', 'project.update'),
    ('system_admin', 'project.delete'), ('system_admin', 'bom.read'),
    ('system_admin', 'bom.update'), ('system_admin', 'assistant.chat'),
    ('system_admin', 'assistant.upload'), ('system_admin', 'assistant.web_search'),
    ('system_admin', 'conversation.read_own'), ('system_admin', 'conversation.read_org'),
    ('system_admin', 'conversation.archive'), ('system_admin', 'member.read'),
    ('system_admin', 'member.manage'), ('system_admin', 'role.manage'),
    ('system_admin', 'audit.read'),
    ('org_admin', 'policy.read'), ('org_admin', 'evidence.read'),
    ('org_admin', 'classification.read'), ('org_admin', 'calculation.run'),
    ('org_admin', 'calculation.read'), ('org_admin', 'project.read'),
    ('org_admin', 'project.create'), ('org_admin', 'project.update'),
    ('org_admin', 'project.delete'), ('org_admin', 'bom.read'),
    ('org_admin', 'bom.update'), ('org_admin', 'assistant.chat'),
    ('org_admin', 'assistant.upload'), ('org_admin', 'assistant.web_search'),
    ('org_admin', 'conversation.read_own'), ('org_admin', 'conversation.read_org'),
    ('org_admin', 'conversation.archive'), ('org_admin', 'member.read'),
    ('org_admin', 'member.manage'), ('org_admin', 'role.manage'),
    ('org_admin', 'audit.read'),
    ('policy_editor', 'policy.read'), ('policy_editor', 'policy.create'),
    ('policy_editor', 'policy.update'), ('policy_editor', 'evidence.read'),
    ('policy_editor', 'evidence.manage'), ('policy_editor', 'classification.read'),
    ('policy_reviewer', 'policy.read'), ('policy_reviewer', 'policy.publish'),
    ('policy_reviewer', 'evidence.read'), ('policy_reviewer', 'audit.read'),
    ('analyst', 'policy.read'), ('analyst', 'evidence.read'),
    ('analyst', 'classification.read'), ('analyst', 'calculation.run'),
    ('analyst', 'calculation.read'), ('analyst', 'project.read'),
    ('analyst', 'bom.read'), ('analyst', 'assistant.chat'),
    ('analyst', 'assistant.upload'), ('analyst', 'assistant.web_search'),
    ('analyst', 'conversation.read_own'), ('analyst', 'conversation.archive'),
    ('project_manager', 'policy.read'), ('project_manager', 'classification.read'),
    ('project_manager', 'calculation.run'), ('project_manager', 'calculation.read'),
    ('project_manager', 'project.read'), ('project_manager', 'project.create'),
    ('project_manager', 'project.update'), ('project_manager', 'project.delete'),
    ('project_manager', 'bom.read'), ('project_manager', 'bom.update'),
    ('project_manager', 'assistant.chat'), ('project_manager', 'assistant.upload'),
    ('project_manager', 'conversation.read_own'), ('project_manager', 'conversation.archive'),
    ('viewer', 'policy.read'), ('viewer', 'evidence.read'),
    ('viewer', 'classification.read'), ('viewer', 'calculation.read'),
    ('viewer', 'project.read'), ('viewer', 'bom.read'),
    ('viewer', 'conversation.read_own'),
    ('audit_reader', 'policy.read'), ('audit_reader', 'evidence.read'),
    ('audit_reader', 'calculation.read'), ('audit_reader', 'project.read'),
    ('audit_reader', 'conversation.read_org'), ('audit_reader', 'audit.read')
)
INSERT INTO iam.role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role_permissions rp
JOIN iam.role r ON r.role_key = rp.role_key
JOIN iam.permission p ON p.permission_key = rp.permission_key
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- The contract hash intentionally covers the migration identity/version,
-- rather than the SQL file's own self-referential registration statement.
DO $$
DECLARE
  expected_checksum char(64) := encode(digest('0011_iam_core:v1', 'sha256'), 'hex');
  existing_checksum char(64);
  existing_key text;
BEGIN
  SELECT checksum
  INTO existing_checksum
  FROM platform.schema_migration
  WHERE migration_key = '0011_iam_core';

  IF existing_checksum IS NOT NULL THEN
    IF lower(existing_checksum) <> lower(expected_checksum) THEN
      RAISE EXCEPTION
        'Migration 0011_iam_core checksum mismatch: database %, expected %',
        existing_checksum, expected_checksum;
    END IF;
    RETURN;
  END IF;

  SELECT migration_key
  INTO existing_key
  FROM platform.schema_migration
  WHERE version = 11;

  IF existing_key IS NOT NULL AND existing_key <> '0011_iam_core' THEN
    RAISE EXCEPTION
      'Migration version 11 is already registered as %', existing_key;
  END IF;

  INSERT INTO platform.schema_migration (
    migration_key, version, checksum, notes
  )
  VALUES (
    '0011_iam_core', 11, expected_checksum,
    'Stage A+B IAM core: identities, organizations, memberships, RBAC, sessions and invitations.'
  );
END
$$;

COMMIT;
